import apiClient from "@/src/api/http";

export type MaintenanceStatus =
  | "SUBMITTED"
  | "APPROVED"
  | "REJECTED"
  | "COMPLETED";

export interface Maintenance {
  _id: string;
  vehicleId: string;
  agencyId: string;
  maintenanceType: string;
  description: string;
  odometerAtRequest: number | null;
  estimatedCost: number | null;
  actualCost: number | null;
  status: MaintenanceStatus | string;
  createdBy: string;
  submittedBy: string | null;
  approvedBy: string | null;
  rejectedBy: string | null;
  completedBy: string | null;
  submittedAt: string | null;
  approvedAt: string | null;
  rejectedAt: string | null;
  completedAt: string | null;
  workshopName: string | null;
  nextServiceDueAtKm: number | null;
  scheduledServiceDate: string | null;
  autoGenerated: boolean;
  createdAt: string;
  updatedAt: string;
}

export const maintenanceService = {
  // List maintenance by status
  getByStatus: async (status: MaintenanceStatus): Promise<Maintenance[]> => {
    const res = await apiClient.get(`/maintenance`, {
      params: { status },
    });
    return res.data;
  },

  // Get maintenance history/details for a vehicle
  getByVehicle: async (vehicleId: string): Promise<Maintenance[]> => {
    const res = await apiClient.get(`/maintenance/vehicle/${vehicleId}`);
    return res.data;
  },

  // Update maintenance status (APPROVE, REJECT, or COMPLETE)
  updateStatus: async (
    maintenanceId: string,
    payload: { status: MaintenanceStatus; actualCost?: number }
  ): Promise<Maintenance> => {
    const res = await apiClient.patch(
      `/maintenance/${maintenanceId}/status`,
      payload
    );
    return res.data;
  },
};

